import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Orquestrador Automático de Tutoria (PBL)\n",
                "Este notebook extrai sumários de livros de medicina em PDF do Google Drive, mapeia objetivos usando a inteligência do Gemini (Google GenAI SDK), realiza curadoria de vídeos didáticos no YouTube (PT-BR) e gera PDFs consolidados com capas premium."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Instalação de Dependências\n",
                "!pip install pymupdf pypdf reportlab pydantic python-dotenv google-genai httpx --quiet\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Montagem do Google Drive\n",
                "from google.colab import drive\n",
                "drive.mount('/content/drive')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Configuração das APIs (Secrets)\n",
                "import os\n",
                "from google.colab import userdata\n",
                "os.environ['GEMINI_API_KEY'] = userdata.get('GEMINI_API_KEY')\n",
                "os.environ['YOUTUBE_API_KEY'] = userdata.get('YOUTUBE_API_KEY')\n",
                "print('Chaves configuradas com sucesso!')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# === DIAGNÓSTICO: Listar Modelos Disponíveis ===\n",
                "from google import genai\n",
                "import os\n",
                "\n",
                "diag_client = genai.Client(api_key=os.environ.get('GEMINI_API_KEY'))\n",
                "print('=== MODELOS GEMINI FLASH DISPONÍVEIS ===')\n",
                "for model in diag_client.models.list():\n",
                "    name = model.name if hasattr(model, 'name') else str(model)\n",
                "    display = model.display_name if hasattr(model, 'display_name') else ''\n",
                "    if 'flash' in name.lower():\n",
                "        print(f'  ✅ {name}  ({display})')\n",
                "print('=========================================')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Motor do Orquestrador\n",
                "import asyncio\n",
                "import logging\n",
                "import json\n",
                "import os\n",
                "import io\n",
                "import re\n",
                "import random\n",
                "import urllib.parse\n",
                "import httpx\n",
                "import pydantic\n",
                "import fitz\n",
                "from google import genai\n",
                "from google.genai import types\n",
                "from pypdf import PdfReader, PdfWriter, PageObject\n",
                "from reportlab.pdfgen import canvas\n",
                "from reportlab.lib.pagesizes import A4\n",
                "from reportlab.lib import colors\n",
                "from reportlab.lib.units import inch\n",
                "\n",
                "logging.basicConfig(level=logging.INFO, format=\"%(levelname)s: %(message)s\")\n",
                "logging.getLogger(\"pypdf\").setLevel(logging.ERROR)\n",
                "\n",
                "import typing\n",
                "class Corte(pydantic.BaseModel):\n",
                "    arquivo: str\n",
                "    capitulo: str\n",
                "    nivel: typing.Literal['conceito', 'mecanismo', 'clinica']\n",
                "    pagina_inicial: int\n",
                "    pagina_final: int\n",
                "\n",
                "class VideoSugerido(pydantic.BaseModel):\n",
                "    termo_busca: str\n",
                "    video_id: str\n",
                "    titulo_formatado: str\n",
                "\n",
                "class PlanejamentoVideos(pydantic.BaseModel):\n",
                "    termos_busca: list[str]\n",
                "\n",
                "class CuradoriaVideo(pydantic.BaseModel):\n",
                "    video_escolhido_id: str\n",
                "    titulo_formatado: str\n",
                "\n",
                "class Objetivo(pydantic.BaseModel):\n",
                "    numero: str\n",
                "    titulo: str\n",
                "    cortes: list[Corte]\n",
                "    videos: list[VideoSugerido] = []\n",
                "\n",
                "class RoteiroTutoria(pydantic.BaseModel):\n",
                "    objetivos: list[Objetivo]\n",
                "\n",
                "class ValidacaoCorte(pydantic.BaseModel):\n",
                "    pagina_inicial_ajustada: int = pydantic.Field(description=\"Página real onde a explicação técnica do objetivo inicia no PDF\")\n",
                "    pagina_final_ajustada: int = pydantic.Field(description=\"Página real onde a explicação técnica do objetivo termina no PDF\")\n",
                "    resumo_cobertura: str = pydantic.Field(description=\"Síntese curta em 1 frase dos tópicos do objetivo validados no capítulo\")\n",
                "\n",
                "class TocItem(pydantic.BaseModel):\n",
                "    nivel: int\n",
                "    titulo: str\n",
                "    pagina: int\n",
                "\n",
                "class TocExtracted(pydantic.BaseModel):\n",
                "    itens: list[TocItem]\n",
                "\n",
                "def draw_wrapped_text(c, text, width, x, y, font, size, line_height, color):\n",
                "    c.setFont(font, size)\n",
                "    c.setFillColor(color)\n",
                "    words = text.split(' ')\n",
                "    lines = []\n",
                "    current_line = []\n",
                "    for word in words:\n",
                "        current_line.append(word)\n",
                "        if c.stringWidth(' '.join(current_line), font, size) > width:\n",
                "            current_line.pop()\n",
                "            lines.append(' '.join(current_line))\n",
                "            current_line = [word]\n",
                "    if current_line:\n",
                "        lines.append(' '.join(current_line))\n",
                "    for line in lines:\n",
                "        c.drawString(x, y, line)\n",
                "        y -= line_height\n",
                "    return y\n",
                "\n",
                "def is_valid_youtube_id(vid_id):\n",
                "    if not vid_id or vid_id in ['placeholder_id', 'NENHUM']:\n",
                "        return False\n",
                "    return len(vid_id) == 11\n",
                "\n",
                "def create_cover_page(objetivo_numero, objetivo_titulo, videos=None):\n",
                "    if videos is None: videos = []\n",
                "    valid_vids = [v for v in videos if is_valid_youtube_id(getattr(v, 'video_id', ''))]\n",
                "    packet = io.BytesIO()\n",
                "    c = canvas.Canvas(packet, pagesize=A4)\n",
                "    width, height = A4\n",
                "    c.setFillColorRGB(1, 1, 1)\n",
                "    c.rect(0, 0, width, height, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(0.12, 0.53, 0.90)\n",
                "    c.rect(0, 0, 15, height, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(0.1, 0.1, 0.1)\n",
                "    c.setFont(\"Helvetica-Bold\", 46)\n",
                "    c.drawString(60, height - 120, f\"OBJETIVO {objetivo_numero}\")\n",
                "    c.setStrokeColorRGB(0.8, 0.8, 0.8)\n",
                "    c.setLineWidth(1)\n",
                "    c.line(60, height - 140, width - 60, height - 140)\n",
                "    c.setFont(\"Helvetica\", 16)\n",
                "    c.setFillColorRGB(0.4, 0.4, 0.4)\n",
                "    c.drawString(60, height - 170, \"ROTEIRO DE TUTORIA\")\n",
                "    font_size = 22\n",
                "    line_height = 30\n",
                "    if len(objetivo_titulo) > 150:\n",
                "        font_size = 18\n",
                "        line_height = 24\n",
                "    if len(objetivo_titulo) > 250:\n",
                "        font_size = 14\n",
                "        line_height = 18\n",
                "    end_y = draw_wrapped_text(c, objetivo_titulo, width - 120, 60, height - 230, \"Helvetica-Bold\", font_size, line_height, colors.black)\n",
                "    if valid_vids:\n",
                "        vy = min(end_y - 40, height - 300)\n",
                "        c.setFont(\"Helvetica-Bold\", 14)\n",
                "        c.setFillColorRGB(0.12, 0.53, 0.90)\n",
                "        c.drawString(60, vy, \"Vídeos Sugeridos:\")\n",
                "        vy -= 25\n",
                "        for vid in valid_vids[:5]:\n",
                "            if vy < 70: break\n",
                "            url = f\"https://youtube.com/watch?v={vid.video_id}\"\n",
                "            c.setFont(\"Helvetica\", 11)\n",
                "            c.setFillColorRGB(0.3, 0.3, 0.3)\n",
                "            c.drawString(60, vy, \"•\")\n",
                "            c.setFont(\"Helvetica-BoldOblique\", 11)\n",
                "            c.setFillColorRGB(0.06, 0.45, 0.85)\n",
                "            c.drawString(75, vy, f\"{vid.titulo_formatado}\")\n",
                "            text_width = c.stringWidth(f\"{vid.titulo_formatado}\", \"Helvetica-BoldOblique\", 11)\n",
                "            line_end_x = min(530, 75 + text_width)\n",
                "            c.setStrokeColorRGB(0.06, 0.45, 0.85)\n",
                "            c.setLineWidth(0.6)\n",
                "            c.line(75, vy - 2, line_end_x, vy - 2)\n",
                "            c.linkURL(url, (75, vy - 2, line_end_x, vy + 10), relative=0)\n",
                "            vy -= 24\n",
                "    c.setFont(\"Helvetica-Oblique\", 10)\n",
                "    c.setFillColorRGB(0.6, 0.6, 0.6)\n",
                "    c.drawString(60, 40, \"© Conteúdo Autoral • João Gabriel R. Trovão\")\n",
                "    c.save()\n",
                "    packet.seek(0)\n",
                "    return PdfReader(packet).pages[0]\n",
                "\n",
                "def create_separator_page(livro, capitulo):\n",
                "    packet = io.BytesIO()\n",
                "    c = canvas.Canvas(packet, pagesize=A4)\n",
                "    width, height = A4\n",
                "    c.setFillColorRGB(1, 1, 1)\n",
                "    c.rect(0, 0, width, height, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(0.12, 0.53, 0.90)\n",
                "    c.rect(40, height/2 + 20, width - 80, 60, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(1, 1, 1)\n",
                "    c.setFont(\"Helvetica-Bold\", 24)\n",
                "    c.drawCentredString(width/2, height/2 + 40, \"REFERÊNCIA\")\n",
                "    draw_wrapped_text(c, f\"{livro}\", width - 100, 50, height/2 - 20, \"Helvetica\", 16, 22, colors.dimgrey)\n",
                "    draw_wrapped_text(c, capitulo, width - 100, 50, height/2 - 60, \"Helvetica-Bold\", 18, 26, colors.black)\n",
                "    c.save()\n",
                "    packet.seek(0)\n",
                "    return PdfReader(packet).pages[0]\n",
                "\n",
                "async def extract_toc_with_gemini(client, pdf_path: str) -> list:\n",
                "    try:\n",
                "        doc = fitz.open(pdf_path)\n",
                "        toc_text = \"\"\n",
                "        toc_pages = []\n",
                "        max_scan = min(35, len(doc))\n",
                "        for i in range(max_scan):\n",
                "            page_text = doc[i].get_text(\"text\")\n",
                "            page_lower = page_text.lower()\n",
                "            if any(kw in page_lower for kw in [\"sumário\", \"sumario\", \"índice\", \"indice\", \"table of contents\", \"conteúdo\", \"conteudo\"]):\n",
                "                toc_pages.append(i)\n",
                "        if toc_pages:\n",
                "            selected_indices = set()\n",
                "            for p in toc_pages:\n",
                "                for offset in range(-1, 5):\n",
                "                    idx = p + offset\n",
                "                    if 0 <= idx < len(doc):\n",
                "                        selected_indices.add(idx)\n",
                "            for idx in sorted(selected_indices):\n",
                "                toc_text += f\"\\n--- PÁGINA {idx+1} ---\\n\" + doc[idx].get_text(\"text\")\n",
                "        else:\n",
                "            for i in range(min(25, len(doc))):\n",
                "                toc_text += f\"\\n--- PÁGINA {i+1} ---\\n\" + doc[i].get_text(\"text\")\n",
                "        doc.close()\n",
                "        if not toc_text.strip(): return []\n",
                "            \n",
                "        sys_prompt = \"\"\"[O] - OBJETIVO\n",
                "Atuar como um especialista em estruturação de metadados, extraindo o Sumário (Table of Contents - TOC) exato e completo de livros de medicina.\n",
                "\n",
                "[C] - CONTEXTO\n",
                "O texto fornecido representa as páginas iniciais do livro contendo o Sumário ou Índice. As quebras de página estão indicadas no texto.\n",
                "\n",
                "[A] - AÇÕES\n",
                "1. Varra o texto buscando a seção \"Sumário\" ou \"Índice\".\n",
                "2. Extraia exaustivamente CADA capítulo e subseção listados no sumário.\n",
                "3. Para cada item, determine o Nível Hierárquico (ex: Parte I = 1, Capítulo = 2, Subseção = 3).\n",
                "4. Extraia o Título do item fielmente.\n",
                "5. Extraia o número da PÁGINA correspondente (tente retornar a página real do PDF, considerando os deslocamentos do sumário).\n",
                "\n",
                "[N] - NORMAS (CRÍTICO)\n",
                "- POSITIVO (COBERTURA COMPLETA): É OBRIGATÓRIO extrair a lista COMPLETA de capítulos do sumário, do primeiro ao ÚLTIMO capítulo listado (ex: Capítulo 1 até Capítulo 30+). NUNCA interrompa a extração nos primeiros capítulos.\n",
                "- NEGATIVO: NUNCA invente itens ou pule seções do sumário.\n",
                "- POSITIVO: Siga estritamente o Schema JSON exigido (TocExtracted).\n",
                "\n",
                "[E] - EXEMPLOS\n",
                "Input: \"...Parte I - Princípios. 1. Biologia Celular... 14. 13. Invasão Tumoral e Metástase... 245...\"\n",
                "Output:\n",
                "Nivel: 1, Titulo: \"Parte I - Princípios\", Pagina: 14\n",
                "Nivel: 2, Titulo: \"13. Invasão Tumoral e Metástase\", Pagina: 245\n",
                "\n",
                "[S] - SAÍDA\n",
                "Retorne OBRIGATORIAMENTE os dados estruturados conforme o JSON Schema exigido (TocExtracted).\"\"\"\n",
                "\n",
                "        logging.info(f\"Extraindo TOC de {os.path.basename(pdf_path)} via LLM...\")\n",
                "        prompt = f\"TEXTO DO SUMÁRIO DO LIVRO:\\n{toc_text}\"\n",
                "        data = await call_gemini_with_fallback(client, prompt, sys_prompt, TocExtracted, max_retries=4)\n",
                "        \n",
                "        toc = []\n",
                "        if data and data.itens:\n",
                "            for item in data.itens:\n",
                "                toc.append([item.nivel, item.titulo, item.pagina])\n",
                "        return toc\n",
                "    except Exception as e:\n",
                "        logging.error(f\"Erro na extração de TOC via LLM para {pdf_path}: {e}\")\n",
                "        return []\n",
                "\n",
                "async def get_pdfs_tocs(client, folder_path):\n",
                "    tocs = {}\n",
                "    for filename in os.listdir(folder_path):\n",
                "        if filename.lower().endswith(\".pdf\"):\n",
                "            filepath = os.path.join(folder_path, filename)\n",
                "            try:\n",
                "                doc = fitz.open(filepath)\n",
                "                toc = doc.get_toc()\n",
                "                doc.close()\n",
                "                if not toc or len(toc) < 15:\n",
                "                    print(f\"⚠️ O arquivo {filename} não possui um sumário digital válido. Extraindo via IA...\")\n",
                "                    toc_raw = await extract_toc_with_gemini(client, filepath)\n",
                "                    toc = []\n",
                "                    if toc_raw:\n",
                "                        offset = obter_offset_pdf(filepath, OFFSETS_MANUAIS)\n",
                "                        for item in toc_raw:\n",
                "                            nivel, titulo, pag_impressa = item\n",
                "                            pag_fisica = pag_impressa\n",
                "                            if isinstance(pag_impressa, int) and offset > 0:\n",
                "                                pag_fisica = pag_impressa + offset\n",
                "                            toc.append([nivel, titulo, pag_fisica])\n",
                "                tocs[filename] = toc\n",
                "            except Exception as e:\n",
                "                logging.error(f\"Erro ao ler TOC de {filename}: {e}\")\n",
                "    return tocs\n",
                "\n",
                "def merge_and_sort_cortes(cortes):\n",
                "    if not cortes: return []\n",
                "    from collections import defaultdict\n",
                "    grouped = defaultdict(list)\n",
                "    for c in cortes:\n",
                "        # Preservação estrita da identidade do capítulo: agrupamos por (arquivo, capitulo)\n",
                "        # para evitar que capítulos diferentes (ex: Cap. 12 e Cap. 13) sejam mesclados e percam a página divisora\n",
                "        grouped[(c.arquivo, c.capitulo)].append(c)\n",
                "    merged = []\n",
                "    for (arquivo, capitulo), lista in grouped.items():\n",
                "        lista.sort(key=lambda x: x.pagina_inicial)\n",
                "        curr = lista[0]\n",
                "        for nxt in lista[1:]:\n",
                "            if nxt.pagina_inicial <= curr.pagina_final + 1:\n",
                "                curr.pagina_final = max(curr.pagina_final, nxt.pagina_final)\n",
                "            else:\n",
                "                merged.append(curr)\n",
                "                curr = nxt\n",
                "        merged.append(curr)\n",
                "    merged.sort(key=lambda x: (x.pagina_inicial, {\"conceito\": 0, \"mecanismo\": 1, \"clinica\": 2}.get(x.nivel, 99)))\n",
                "    return merged\n",
                "\n",
                "def agrupar_objetivos(objetivos):\n",
                "    def get_pages(obj):\n",
                "        pages = set()\n",
                "        for c in obj.cortes:\n",
                "            for p in range(c.pagina_inicial, max(c.pagina_inicial, c.pagina_final) + 1):\n",
                "                pages.add(f\"{c.arquivo}_{p}\")\n",
                "        return pages\n",
                "    grupos = []\n",
                "    for obj in objetivos:\n",
                "        merged = False\n",
                "        obj_pages = get_pages(obj)\n",
                "        for grupo in grupos:\n",
                "            grupo_pages = set()\n",
                "            for g_obj in grupo:\n",
                "                grupo_pages.update(get_pages(g_obj))\n",
                "            if not obj_pages or not grupo_pages: continue\n",
                "            overlap = len(obj_pages.intersection(grupo_pages)) / len(obj_pages.union(grupo_pages))\n",
                "            if overlap > 0.3:\n",
                "                grupo.append(obj)\n",
                "                merged = True\n",
                "                break\n",
                "        if not merged:\n",
                "            grupos.append([obj])\n",
                "    objetivos_mesclados = []\n",
                "    for grupo in grupos:\n",
                "        if len(grupo) == 1:\n",
                "            objetivos_mesclados.append(grupo[0])\n",
                "        else:\n",
                "            numeros = \" e \".join([g.numero for g in grupo])\n",
                "            titulo = \"  |  \".join([f\"[{g.numero}] {g.titulo}\" for g in grupo])\n",
                "            cortes = []\n",
"            videos = []\n",
                "            for g in grupo:\n",
                "                cortes.extend(g.cortes)\n",
                "                if hasattr(g, 'videos') and g.videos:\n",
                "                    videos.extend(g.videos)\n",
                "            objetivos_mesclados.append(Objetivo(numero=numeros, titulo=titulo, cortes=cortes, videos=videos))\n",
                "    return objetivos_mesclados\n",
                "\n",
                "OFFSETS_MANUAIS = {\n",
                "    \"SAito.pdf\": 15\n",
                "}\n",
                "\n",
                "def obter_offset_pdf(source_pdf, manual_offsets=None):\n",
                "    if manual_offsets is None:\n",
                "        manual_offsets = OFFSETS_MANUAIS\n",
                "    filename = os.path.basename(source_pdf)\n",
                "    if filename in manual_offsets:\n",
                "        return manual_offsets[filename]\n",
                "    try:\n",
                "        doc = fitz.open(source_pdf)\n",
                "        toc = doc.get_toc()\n",
                "        if toc:\n",
                "            for item in toc:\n",
                "                phys_page = item[2]\n",
                "                if isinstance(phys_page, int) and 1 <= phys_page <= len(doc):\n",
                "                    text = doc[phys_page - 1].get_text(\"text\")\n",
                "                    lines = [line.strip() for line in text.split('\\n') if line.strip().isdigit()]\n",
                "                    for num_str in lines:\n",
                "                        printed_num = int(num_str)\n",
                "                        diff = phys_page - printed_num\n",
                "                        if 0 <= diff < 100:\n",
                "                            doc.close()\n",
                "                            return diff\n",
                "        doc.close()\n",
                "    except Exception as e:\n",
                "        logging.warning(f\"Erro ao autodetectar offset de {filename}: {e}\")\n",
                "    return 0\n",
                "\n",
                "def reconciliar_e_calcular_limites_corte(source_pdf, capitulo_nome, pag_ini_gemini, pag_fim_gemini):\n",
                "    offset = obter_offset_pdf(source_pdf, OFFSETS_MANUAIS)\n",
                "    try:\n",
                "        doc = fitz.open(source_pdf)\n",
                "        toc = doc.get_toc()\n",
                "        total_pages = len(doc)\n",
                "        doc.close()\n",
                "        \n",
                "        p_ini_fisica_gemini = pag_ini_gemini + offset\n",
                "        p_fim_fisica_gemini = pag_fim_gemini + offset\n",
                "        \n",
                "        if toc:\n",
                "            toc_match_page = None\n",
                "            cap_num_match = re.search(r'^\\s*(\\d+)', capitulo_nome)\n",
                "            for item in toc:\n",
                "                title = str(item[1])\n",
                "                page_num = item[2]\n",
                "                if isinstance(page_num, int):\n",
                "                    if capitulo_nome.lower().strip() in title.lower().strip() or title.lower().strip() in capitulo_nome.lower().strip():\n",
                "                        toc_match_page = page_num\n",
                "                        break\n",
                "                    elif cap_num_match:\n",
                "                        item_num_match = re.search(r'^\\s*(\\d+)', title)\n",
                "                        if item_num_match and item_num_match.group(1) == cap_num_match.group(1):\n",
                "                            toc_match_page = page_num\n",
                "                            break\n",
                "            p_ini_real = p_ini_fisica_gemini\n",
                "            if toc_match_page is not None and abs(toc_match_page - p_ini_fisica_gemini) > 3:\n",
                "                logging.info(f\"ℹ️ Self-Healing TOC: Reconciliando início de '{capitulo_nome}' de física {p_ini_fisica_gemini} para {toc_match_page} (Página Física do TOC).\")\n",
                "                p_ini_real = toc_match_page\n",
                "            next_pages = sorted([item[2] for item in toc if isinstance(item[2], int) and item[2] > p_ini_real])\n",
                "            if next_pages:\n",
                "                p_fim_real = next_pages[0] - 1\n",
                "            else:\n",
                "                p_fim_real = max(p_fim_fisica_gemini, total_pages)\n",
                "            return p_ini_real, max(p_fim_fisica_gemini, p_fim_real)\n",
                "    except Exception as e:\n",
                "        logging.warning(f\"Falha na reconciliação de TOC para {source_pdf}: {e}\")\n",
                "    return pag_ini_gemini + offset, max(pag_fim_gemini + offset, pag_ini_gemini + offset + 15)\n",
                "\n",
                "def gerar_pdfs(roteiro, pdfs_dir, output_dir):\n",
                "    os.makedirs(output_dir, exist_ok=True)\n",
                "    objetivos_processados = agrupar_objetivos(roteiro.objetivos)\n",
                "    for obj in objetivos_processados:\n",
                "        obj_pdf_path = os.path.join(output_dir, f\"Objetivo {obj.numero}.pdf\")\n",
                "        writer = PdfWriter()\n",
                "        writer.add_page(create_cover_page(obj.numero, obj.titulo, getattr(obj, 'videos', [])))\n",
                "        cortes = merge_and_sort_cortes(obj.cortes)\n",
                "        last_book_chapter = \"\"\n",
                "        for corte in cortes:\n",
                "            source_pdf = os.path.join(pdfs_dir, corte.arquivo)\n",
                "            if not os.path.exists(source_pdf): continue\n",
                "            \n",
                "            # Reconciliação Defensiva e Aplicação de Offset (Página Impressa -> Página Física)\n",
                "            p_ini_fisica, p_fim_fisica = reconciliar_e_calcular_limites_corte(source_pdf, corte.capitulo, corte.pagina_inicial, corte.pagina_final)\n",
                "            logging.info(f\"ℹ️ Fatiando '{corte.capitulo}' em '{corte.arquivo}': Impresso {corte.pagina_inicial}–{corte.pagina_final} -> Físico {p_ini_fisica}–{p_fim_fisica}.\")\n",
                "                \n",
                "            curr_bc = f\"{corte.arquivo}_{corte.capitulo}\"\n",
                "            if curr_bc != last_book_chapter:\n",
                "                writer.add_page(create_separator_page(corte.arquivo, corte.capitulo))\n",
                "                last_book_chapter = curr_bc\n",
                "            reader = PdfReader(source_pdf)\n",
                "            p_ini, p_fim = max(0, p_ini_fisica - 1), min(len(reader.pages), max(p_ini_fisica, p_fim_fisica))\n",
                "            for p_num in range(p_ini, p_fim): writer.add_page(reader.pages[p_num])\n",
                "        with open(obj_pdf_path, \"wb\") as f: writer.write(f)\n",
                "        logging.info(f\"Gerado: {obj_pdf_path}\")\n",
                "\n",
                "async def call_gemini_with_fallback(client, contents, system_instruction, response_schema, max_retries=4):\n",
                "    models = ['gemini-3.5-flash-lite', 'gemini-3.6-flash', 'gemini-2.5-flash', 'gemini-3.5-flash']\n",
                "    \n",
                "    for model_to_use in models:\n",
                "        for tentativa in range(max_retries):\n",
                "            try:\n",
                "                response = await client.aio.models.generate_content(\n",
                "                    model=model_to_use,\n",
                "                    contents=contents,\n",
                "                    config=types.GenerateContentConfig(\n",
                "                        system_instruction=system_instruction,\n",
                "                        response_mime_type=\"application/json\",\n",
                "                        response_schema=response_schema,\n",
                "                    )\n",
                "                )\n",
                "                if not response.parsed:\n",
                "                    raise ValueError(\"O modelo não retornou um JSON válido.\")\n",
                "                return response.parsed\n",
                "            except Exception as e:\n",
                "                error_msg = str(e)\n",
                "                is_critical = any(term in error_msg for term in ['400', '401', 'InvalidArgument', 'PermissionDenied'])\n",
                "                if is_critical:\n",
                "                    logging.error(f\"Erro fatal (Client Error): {e}. Abortando imediatamente (Fail-Fast).\")\n",
                "                    raise e\n",
                "                if \"404\" in error_msg or \"not found\" in error_msg.lower() or \"no longer available\" in error_msg.lower():\n",
                "                    logging.warning(f\"Modelo {model_to_use} indisponível (Erro 404). Pulando para o próximo modelo...\")\n",
                "                    break\n",
                "                exponent_cap = 2 ** tentativa\n",
                "                sleep_time = random.uniform(0, exponent_cap)\n",
                "                logging.error(f\"Erro na API do Gemini com {model_to_use} (Tentativa {tentativa+1}/{max_retries}): {e}\")\n",
                "                logging.info(f\"Aguardando {sleep_time:.2f}s antes da próxima tentativa...\")\n",
                "                await asyncio.sleep(sleep_time)\n",
                "            \n",
                "    return None\n",
                "\n",
                "async def process_roteiro(objetivos_text, tocs, refs_dir):\n",
                "    contexto = \"SUMÁRIOS:\\n\"\n",
                "    for arquivo, toc in tocs.items():\n",
                "        if toc:\n",
                "            source_pdf = os.path.join(refs_dir, arquivo) if refs_dir else arquivo\n",
                "            offset = obter_offset_pdf(source_pdf, OFFSETS_MANUAIS)\n",
                "            contexto += f\"Livro: {arquivo} (Offset de pré-texto: {offset} páginas)\\n\"\n",
                "            for item in toc:\n",
                "                phys_page = item[2]\n",
                "                printed_page = max(1, phys_page - offset) if isinstance(phys_page, int) else phys_page\n",
                "                contexto += f\"{'  '*(item[0]-1)}- {item[1]} (Página Impressa no Livro: {printed_page})\\n\"\n",
                "    system_prompt = \"\"\"[O] - OBJETIVO\n",
                "Você é um Monitor Acadêmico rigoroso e Orquestrador de Tutoria (PBL) de Medicina. Sua meta é analisar Objetivos de Aprendizagem e cruzá-los com a base de sumários fornecida para gerar recortes de leitura milimetricamente precisos, abrangentes e sem omissões.\n",
                "\n",
                "[C] - CONTEXTO\n",
                "Você recebe os sumários (TOC) extraídos dos livros em PDF (Ground Truth). Cada linha possui Nível Hierárquico, Título do Capítulo/Seção e Página Impressa no Livro (número impresso no rodapé).\n",
                "\n",
                "[A] - AÇÕES (EXECUTE NESTA ORDEM)\n",
                "1. Fragmentação Semântica: Isole cada Objetivo de Aprendizagem e identifique seus temas centrais.\n",
                "2. Varredura nos Sumários: Para cada objetivo, busque nos sumários por palavras-chave e subseções correspondentes.\n",
                "3. Avaliação de Escopo (Regra dos 60%):\n",
                "   - Se o capítulo mapeado for a fonte primária e cobrir mais de 60% do tema do objetivo -> cite o capítulo completo (ex: pp. 245–260).\n",
                "   - Se apenas uma subseção específica for relevante -> afunile para a subseção (ex: pp. 225–244).\n",
                "   - Em caso de dúvida, prefira o capítulo completo — é menos prejudicial incluir contexto extra do que deixar lacunas.\n",
                "4. Mapeamento Multicapítulo: Se o objetivo abordar temas espalhados em capítulos/subseções diferentes (ex: Angiogênese no Cap. 12 e Metástase no Cap. 13), gere MÚLTIPLOS CORTES (um para cada capítulo/subseção).\n",
                "5. Cálculo Fiel de Limites: Defina `pagina_inicial` e `pagina_final` utilizando EXCLUSIVAMENTE a numeração de Páginas Impressas presente nos sumários (sendo `pagina_final` exatamente a página impressa do capítulo seguinte menos 1).\n",
                "\n",
                "[N] - NORMAS (CRÍTICO)\n",
                "- REGRA DE OURO (PÁGINAS IMPRESSAS DO LIVRO): Use EXCLUSIVAMENTE a numeração de Página Impressa fornecida no sumário. NUNCA aplique offsets por conta própria.\n",
                "- POSITIVO (COBERTURA COMPLETA): Se um objetivo tratar de 'metástase' e 'angiogênese', e existirem o Cap. 12 (Angiogênese Tumoral) e o Cap. 13 (Invasão Tumoral e Metástase), inclua AMBOS os cortes no mesmo objetivo.\n",
                "- POSITIVO: Cite o intervalo de páginas completo baseado nas páginas impressas (ex: Cap 12 = pagina_inicial: 225, pagina_final: 244; Cap 13 = pagina_inicial: 245, pagina_final: 260).\n",
                "- NEGATIVO: NUNCA retorne pagina_final igual a pagina_inicial (ex: 245 -> 245).\n",
                "- NEGATIVO: NUNCA invente páginas ou títulos que não estejam nos sumários fornecidos.\n",
                "\n",
                "[E] - EXEMPLOS (FEW-SHOT DE ALTA QUALIDADE)\n",
                "Exemplo 1 (Objetivo Composto - Angiogênese e Metástase):\n",
                "Objetivo: \"Explicar a fisiopatologia da metástase, incluindo as etapas da cascata metastática e o papel da angiogênese no estabelecimento de tumores secundários.\"\n",
                "Sumário Disponível (Páginas Impressas no Livro):\n",
                "  - Cap. 12: Angiogênese Tumoral (Página Impressa no Livro: 225)\n",
                "  - Cap. 13: Invasão Tumoral e Metástase (Página Impressa no Livro: 245)\n",
                "  - Cap. 14: Diagnóstico das Neoplasias (Página Impressa no Livro: 261)\n",
                "\n",
                "Output (Dois Cortes Mapeados em Páginas Impressas):\n",
                "Corte 1: capitulo: \"12 Angiogênese Tumoral\", pagina_inicial: 225, pagina_final: 244, nivel: \"mecanismo\"\n",
                "Corte 2: capitulo: \"13 Invasão Tumoral e Metástase\", pagina_inicial: 245, pagina_final: 260, nivel: \"mecanismo\"\n",
                "\n",
                "Exemplo 2 (Marcadores Tumorais - Capítulo Completo):\n",
                "Objetivo: \"Analisar a utilidade clínica e as limitações de marcadores tumorais no diagnóstico, seguimento do tratamento e detecção de recidivas.\"\n",
                "Sumário Disponível (Páginas Impressas no Livro):\n",
                "  - Cap. 17: Biomarcadores no Câncer (Página Impressa no Livro: 316)\n",
                "  - Cap. 18: Terapia Alvo (Página Impressa no Livro: 329)\n",
                "\n",
                "Output:\n",
                "Corte 1: capitulo: \"17 Biomarcadores no Câncer\", pagina_inicial: 316, pagina_final: 328, nivel: \"clinica\"\n",
                "\n",
                "[S] - SAÍDA\n",
                "Retorne OBRIGATORIAMENTE os dados estruturados conforme o JSON Schema exigido pela API (`RoteiroTutoria`). Retorne o JSON puro e direto.\"\"\"\n",
                "    api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "    client = genai.Client(api_key=api_key)\n",
                "    parsed_response = await call_gemini_with_fallback(\n",
                "        client=client,\n",
                "        contents=f\"{contexto}\\n\\nOBJETIVOS:\\n{objetivos_text}\",\n",
                "        system_instruction=system_prompt,\n",
                "        response_schema=RoteiroTutoria\n",
                "    )\n",
                "    return parsed_response\n",
                "\n",
                "def extrair_texto_paginas(pdf_path, p_ini, p_fim):\n",
                "    try:\n",
                "        doc = fitz.open(pdf_path)\n",
                "        text = \"\"\n",
                "        start = max(0, p_ini - 1)\n",
                "        end = min(len(doc), max(p_ini, p_fim))\n",
                "        for i in range(start, end):\n",
                "            text += f\"\\n--- PÁGINA {i+1} ---\\n\"\n",
                "            text += doc[i].get_text(\"text\")\n",
                "        doc.close()\n",
                "        return text\n",
                "    except Exception as e:\n",
                "        logging.error(f\"Erro extraindo texto: {e}\")\n",
                "        return \"\"\n",
                "\n",
                "async def refinar_roteiro(roteiro, refs_dir):\n",
                "    api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "    client = genai.Client(api_key=api_key)\n",
                "    sys_prompt = \"\"\"[O] - OBJETIVO\n",
                "Atue como Validador Pedagógico de Leitura (PBL). Sua missão é analisar o texto do capítulo mapeado pelo Agente 1, confirmar a presença dos tópicos do Objetivo de Aprendizagem e refinar os limites de páginas (inicial e final) para cobrir a explicação técnica completa sem mutilar o capítulo.\n",
                "\n",
                "[C] - CONTEXTO\n",
                "Você recebe dois dados de entrada (Ground Truth):\n",
                "1. O Objetivo de Aprendizagem.\n",
                "2. O Texto Extraído do capítulo em PDF, onde cada transição de página é demarcada pelo marcador '--- PÁGINA X ---'.\n",
                "\n",
                "[A] - AÇÕES\n",
                "Pense passo a passo:\n",
                "1. Desconstrua os eixos semânticos centrais do objetivo.\n",
                "2. Varra o Texto Extraído e identifique a primeira página contendo explicação técnica direta para o objetivo. Salve-a como `pagina_inicial_ajustada`.\n",
                "3. Avance a leitura até a página onde a explicação técnica do tópico se conclui. Salve-a como `pagina_final_ajustada`.\n",
                "4. Elabore uma síntese curta (1 frase) no campo `resumo_cobertura` destacando os conceitos validados no capítulo.\n",
                "\n",
                "[N] - NORMAS (CRÍTICO)\n",
                "- POSITIVO (ACEITAÇÃO GARANTIDA): Você NUNCA descarta o capítulo. O capítulo fornecido é considerado relevante para o estudo. Sua função é calibrar a extensão e resumir a cobertura.\n",
                "- NEGATIVO: NUNCA crie um corte de apenas 1 página (ex: 260 -> 260) para um objetivo abrangente. O corte DEVE cobrir a extensão útil completa (mínimo recomendável de 3 a 12 páginas contíguas).\n",
                "- NEGATIVO: NUNCA invente números de página fora das marcas '--- PÁGINA X ---'.\n",
                "- POSITIVO: Se o texto do capítulo aborda o objetivo da primeira à última página, retorne exatamente o intervalo de páginas recebido.\n",
                "\n",
                "[E] - EXEMPLOS\n",
                "Input (Simplificado):\n",
                "Objetivo: \"Fisiopatologia da metástase e cascata metastática.\"\n",
                "Texto Extraído: (Páginas 245 a 259 do livro)\n",
                "\n",
                "Output:\n",
                "`pagina_inicial_ajustada`: 245, `pagina_final_ajustada`: 259, `resumo_cobertura`: \"Validados os conceitos de invasão tecidual, intravasamento, disseminação vascular e angiogênese tumoral.\"\n",
                "\n",
                "[S] - SAÍDA\n",
                "Retorne OBRIGATORIAMENTE os dados estruturados conforme o JSON Schema exigido (`ValidacaoCorte`).\"\"\"\n",
                "    for obj in roteiro.objetivos:\n",
                "        for corte in obj.cortes:\n",
                "            source_pdf = os.path.join(refs_dir, corte.arquivo)\n",
                "            if not os.path.exists(source_pdf):\n",
                "                continue\n",
                "            texto = extrair_texto_paginas(source_pdf, corte.pagina_inicial, corte.pagina_final)\n",
                "            if not texto.strip():\n",
                "                continue\n",
                "            prompt = f\"OBJETIVO: {obj.titulo}\\n\\nTEXTO EXTRAÍDO:\\n{texto[:150000]}\"\n",
                "            parsed_response = await call_gemini_with_fallback(\n",
                "                client=client,\n",
                "                contents=prompt,\n",
                "                system_instruction=sys_prompt,\n",
                "                response_schema=ValidacaoCorte\n",
                "            )\n",
                "            if parsed_response:\n",
                "                p_ini = parsed_response.pagina_inicial_ajustada\n",
                "                p_fim = parsed_response.pagina_final_ajustada\n",
                "                if p_ini > 0 and p_fim >= p_ini:\n",
                "                    corte.pagina_inicial = p_ini\n",
                "                    corte.pagina_final = p_fim\n",
                "                logging.info(f\"✅ Agente 2 [Objetivo {obj.numero}]: {parsed_response.resumo_cobertura} (p. {corte.pagina_inicial} a {corte.pagina_final})\")\n",
                "    return roteiro\n",
                "\n",
                "async def planejar_videos(client, objetivo_titulo):\n",
                "    sys_prompt = \"\"\"**OBJETIVO:**\n",
                "Atuar como um Planejador Pedagógico Clínico. Sua missão é ler um Objetivo de Aprendizagem e fragmentá-lo em termos de busca (queries) estritos, que serão utilizados para encontrar videoaulas essenciais no YouTube em Português.\n",
                "\n",
                "**CONTEXTO:**\n",
                "Você receberá o enunciado completo de um Objetivo de Aprendizagem de um Roteiro de Tutoria (PBL) de Medicina.\n",
                "\n",
                "**AÇÕES:**\n",
                "1. Desconstrua o objetivo para identificar seus eixos principais (ex: Fisiopatologia, Diagnóstico, Farmacologia, Epidemiologia).\n",
                "2. Avalie a necessidade real de suporte visual ou em vídeo para cada eixo.\n",
                "3. Se o objetivo contiver múltiplos agentes, patologias ou drogas (ex: Cocaína, Maconha, Álcool), fragmente a pesquisa gerando um termo de busca separado para cada entidade.\n",
                "4. Para cada eixo/entidade relevante, gere um termo de busca clínico e direto em Português (ex: \"Intoxicação por Cocaína Fisiopatologia\").\n",
                "\n",
                "**NORMAS:**\n",
                "1. **Contenção Trivial:** É terminantemente PROIBIDO recomendar vídeos para objetivos puramente epidemiológicos, históricos, ou sociológicos.\n",
                "2. **Formatação de Query:** NUNCA inclua as palavras \"medicina\" ou \"aula\" nos termos gerados (o sistema injetará isso automaticamente no backend).\n",
                "3. **Limite de Fragmentação:** Não gere mais do que 4 termos por objetivo.\n",
                "4. **Formato de Saída:** Retorne estritamente o objeto JSON conforme o schema exigido (PlanejamentoVideos).\n",
                "\n",
                "**SAÍDA:**\n",
                "Retornar objeto JSON aderente ao Schema PlanejamentoVideos.\"\"\"\n",
                "    return await call_gemini_with_fallback(client, f\"OBJETIVO:\\n{objetivo_titulo}\", sys_prompt, PlanejamentoVideos)\n",
                "\n",
                "ENGLISH_TERMS = ['pathology', 'surgery', 'lecture', 'overview', 'treatment of', 'management of', 'diagnosis of', 'journal', 'usmle', 'role in', 'review of', 'case report', 'clinical trial', 'definition', 'understanding', 'mechanism of', 'syndrome']\n",
                "\n",
                "def eh_titulo_em_ingles(titulo):\n",
                "    t_lower = titulo.lower()\n",
                "    indicadores_pt = ['aula', 'medicina', 'resumo', 'fisiopatologia', 'tratamento', 'diagnostico', 'diagnóstico', 'doença', 'síndrome', 'sindrome', 'sanar', 'jaleko', 'estrategia', 'estratégia', 'medway', 'afya', 'medcel']\n",
                "    if any(pt in t_lower for pt in indicadores_pt):\n",
                "        return False\n",
                "    return any(eng in t_lower for eng in ENGLISH_TERMS)\n",
                "\n",
                "async def buscar_youtube(termo, api_key):\n",
                "    query = urllib.parse.quote(f\"{termo} medicina aula\")\n",
                "    url = f\"https://www.googleapis.com/youtube/v3/search?part=snippet&q={query}&type=video&maxResults=5&key={api_key}&relevanceLanguage=pt\"\n",
                "    async with httpx.AsyncClient() as client:\n",
                "        try:\n",
                "            r = await client.get(url)\n",
                "            if r.status_code == 200:\n",
                "                data = r.json()\n",
                "                resultados = []\n",
                "                termo_proibidos = [\"música\", \"musica\", \"clipe\", \"official video\", \"video oficial\", \"karaoke\", \"paródia\", \"parodia\", \"rick astley\"]\n",
                "                for item in data.get('items', []):\n",
                "                    snippet = item.get('snippet', {})\n",
                "                    title = snippet.get('title', '')\n",
                "                    t_lower = title.lower()\n",
                "                    if any(p in t_lower for p in termo_proibidos) or eh_titulo_em_ingles(title):\n",
                "                        logging.info(f\"Desconsiderando vídeo inadequado/em inglês no backend: '{title}'\")\n",
                "                        continue\n",
                "                    resultados.append({\n",
                "                        'id': item['id']['videoId'],\n",
                "                        'title': title,\n",
                "                        'channel': snippet.get('channelTitle', ''),\n",
                "                        'description': snippet.get('description', '')\n",
                "                    })\n",
                "                return resultados\n",
                "        except Exception as e:\n",
                "            logging.error(f\"Erro no YouTube API: {e}\")\n",
                "    return []\n",
                "\n",
                "async def avaliar_com_llm(client, termo, resultados):\n",
                "    if not resultados: return None\n",
                "    resultados_txt = \"\"\n",
                "    for i, vid in enumerate(resultados):\n",
                "        resultados_txt += f\"\\nOpção {i+1}:\\n- ID: {vid['id']}\\n- Título: {vid['title']}\\n- Canal: {vid['channel']}\\n- Descrição: {vid['description']}\\n\"\n",
                "    sys_prompt = \"\"\"**OBJETIVO:**\n",
                "Atuar como Curador Acadêmico Médico rigoroso. Sua missão é analisar uma lista de resultados de busca do YouTube e selecionar O MELHOR material (videoaula) para estudantes de medicina e residentes.\n",
                "\n",
                "**CONTEXTO:**\n",
                "Você receberá o TEMA / TERMO DE BUSCA, e as opções retornadas pela API do YouTube, contendo Título, Canal e Descrição.\n",
                "\n",
                "**AÇÕES:**\n",
                "1. Analise o Tema/Termo para entender o foco clínico exigido.\n",
                "2. Varra os metadados (Título, Canal, Descrição) de cada vídeo disponível.\n",
                "3. Classifique a Autoridade do Canal: priorize canais de educação médica consolidados (ex: SanarFlix, Estratégia MED, Medway, Afya, Medcel, Ligas Acadêmicas).\n",
                "4. Eleja a opção de maior profundidade científica.\n",
                "5. Se não houver nenhum candidato aceitável ou em português, defina o ID escolhido como 'NENHUM' e o título formatado vazio.\n",
                "\n",
                "**NORMAS:**\n",
                "1. **Filtro de Leigos:** REJEITE sumariamente vídeos direcionados a pacientes leigos (ex: \"quais os sintomas\", \"como curar\", \"o que é\", \"dicas de saúde\").\n",
                "2. **Filtro de Idioma (ESTRITO):** É TERMINANTEMENTE PROIBIDO selecionar vídeos em inglês, espanhol ou qualquer idioma estrangeiro. A videoaula DEVE ser estritamente em Português do Brasil (PT-BR). Se todas as opções forem em idioma estrangeiro, defina o `video_escolhido_id` obrigatoriamente como 'NENHUM'.\n",
                "3. **Alucinação Zero:** NUNCA invente um ID de vídeo que não esteja explicitamente listado nas opções. O ID retornado DEVE ser uma das opções fornecidas.\n",
                "4. **Formato de Saída:** Retorne estritamente o objeto JSON conforme o schema exigido (CuradoriaVideo).\n",
                "\n",
                "**SAÍDA:**\n",
                "Retornar objeto JSON aderente ao Schema CuradoriaVideo.\"\"\"\n",
                "    prompt = f\"Tema/Termo: {termo}\\n\\nOpções:\\n{resultados_txt}\"\n",
                "    return await call_gemini_with_fallback(client, prompt, sys_prompt, CuradoriaVideo)\n",
                "\n",
                "async def adicionar_videos_ao_roteiro(roteiro):\n",
                "    api_key_youtube = os.environ.get('YOUTUBE_API_KEY')\n",
                "    api_key_gemini = os.environ.get('GEMINI_API_KEY')\n",
                "    if not api_key_youtube:\n",
                "        logging.warning(\"YOUTUBE_API_KEY não encontrada. Pulando curadoria de vídeos.\")\n",
                "        return roteiro\n",
                "    client = genai.Client(api_key=api_key_gemini)\n",
                "    print(\"\\nIniciando Agente 3: Curadoria de Vídeos do YouTube...\")\n",
                "    for obj in roteiro.objetivos:\n",
                "        print(f\"  -> Analisando vídeos para: Objetivo {obj.numero}\")\n",
                "        plan = await planejar_videos(client, obj.titulo)\n",
                "        if plan and plan.termos_busca:\n",
                "            print(f\"     Termos identificados: {plan.termos_busca}\")\n",
                "            for termo in plan.termos_busca:\n",
                "                resultados = await buscar_youtube(termo, api_key_youtube)\n",
                "                valid_ids = {vid['id']: vid['title'] for vid in resultados}\n",
                "                curadoria = await avaliar_com_llm(client, termo, resultados)\n",
                "                if curadoria and curadoria.video_escolhido_id in valid_ids and is_valid_youtube_id(curadoria.video_escolhido_id):\n",
                "                    if not hasattr(obj, 'videos') or obj.videos is None:\n",
                "                        obj.videos = []\n",
                "                    final_title = curadoria.titulo_formatado or valid_ids[curadoria.video_escolhido_id]\n",
                "                    obj.videos.append(VideoSugerido(\n",
                "                        termo_busca=termo,\n",
                "                        video_id=curadoria.video_escolhido_id,\n",
                "                        titulo_formatado=final_title\n",
                "                    ))\n",
                "                    print(f\"     ✅ Vídeo Curado para '{termo}': {final_title}\")\n",
                "                else:\n",
                "                    print(f\"     ⚠️ Nenhum vídeo bom em PT-BR encontrado para '{termo}'.\")\n",
                "    return roteiro\n",
                "\n",
                "async def gerar_esboco(objetivos_text, refs_dir):\n",
                "    api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "    client = genai.Client(api_key=api_key)\n",
                "    print(\"Analisando sumários e consultando a API do Gemini (Agente 1)...\")\n",
                "    tocs = await get_pdfs_tocs(client, refs_dir)\n",
                "    if not tocs:\n",
                "        print(f\"❌ Erro crítico: Nenhum arquivo PDF com sumário foi encontrado na pasta '{refs_dir}'.\")\n",
                "        print(\"Verifique se o caminho da variável PASTA_LIVROS está correto e se há arquivos .pdf dentro dela.\")\n",
                "        return\n",
                "    roteiro = await process_roteiro(objetivos_text, tocs, refs_dir)\n",
                "    if roteiro:\n",
                "        print(\"Validando e calibrando cortes através de leitura de texto (Agente 2)...\")\n",
                "        roteiro = await refinar_roteiro(roteiro, refs_dir)\n",
                "        roteiro = await adicionar_videos_ao_roteiro(roteiro)\n",
                "        with open('roteiro_revisao.json', 'w', encoding='utf-8') as f:\n",
                "            f.write(roteiro.model_dump_json(indent=4))\n",
                "        print(\"✅ Esboço gerado com sucesso!\")\n",
                "        print(\"👉 Dê um clique duplo no arquivo 'roteiro_revisao.json' no menu de Arquivos à esquerda.\")\n",
                "        print(\"👉 Revise as páginas e os cortes. Se algo estiver errado, altere os números e salve (Ctrl+S).\")\n",
                "        print(\"👉 Depois de salvar, rode a célula '6. EXPORTAR PDFs FINAIS'.\")\n",
                "    else:\n",
                "        print(\"❌ Falha ao gerar o roteiro.\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. INSERIR OBJETIVOS E GERAR ESBOÇO\n",
                "# ===================================\n",
                "PASTA_LIVROS = \"/content/drive/MyDrive/Logística - Drive/Tutoria\"\n",
                "PASTA_SAIDA = \"/content/drive/MyDrive/Logística - Drive/Tutoria/saida/Tutoria_Teste\"\n",
                "\n",
                "OBJETIVOS = \"\"\"\n",
                "1. Descrever as drogas ilícitas mais comuns...\n",
                "2. Confrontar os conceitos clínicos e neurobiológicos...\n",
                "\"\"\"\n",
                "\n",
                "await gerar_esboco(OBJETIVOS, PASTA_LIVROS)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. EXPORTAR PDFs FINAIS (Após sua revisão!)\n",
                "# ==========================================\n",
                "import json\n",
                "import os\n",
                "import logging\n",
                "\n",
                "def exportar_pdfs_finais():\n",
                "    print(\"Lendo roteiro_revisao.json...\")\n",
                "    if not os.path.exists('roteiro_revisao.json'):\n",
                "        print(\"❌ Erro: Arquivo roteiro_revisao.json não encontrado. Rode a célula 5 primeiro.\")\n",
                "        return\n",
                "        \n",
                "    with open('roteiro_revisao.json', 'r', encoding='utf-8') as f:\n",
                "        dados = json.load(f)\n",
                "        \n",
                "    # Normalização defensiva de chaves e limpeza de video_ids falsos ('placeholder_id', 'NENHUM')\n",
                "    if isinstance(dados, dict) and \"objetivos\" in dados:\n",
                "        for obj in dados.get(\"objetivos\", []):\n",
                "            if \"titux\" in obj and \"titulo\" not in obj:\n",
                "                print(\"⚠️ Aviso: Chave incorreta 'titux' detectada em objetivo. Corrigindo automaticamente para 'titulo'...\")\n",
                "                obj[\"titulo\"] = obj.pop(\"titux\")\n",
                "            if \"título\" in obj and \"titulo\" not in obj:\n",
                "                obj[\"titulo\"] = obj.pop(\"título\")\n",
                "            if \"title\" in obj and \"titulo\" not in obj:\n",
                "                obj[\"titulo\"] = obj.pop(\"title\")\n",
                "            if \"cortes\" in obj:\n",
                "                for corte in obj.get(\"cortes\", []):\n",
                "                    if \"título\" in corte and \"capitulo\" not in corte:\n",
                "                        corte[\"capitulo\"] = corte.pop(\"título\")\n",
                "                    if \"capítulo\" in corte and \"capitulo\" not in corte:\n",
                "                        corte[\"capitulo\"] = corte.pop(\"capítulo\")\n",
                "            if \"videos\" in obj and isinstance(obj[\"videos\"], list):\n",
                "                obj[\"videos\"] = [v for v in obj[\"videos\"] if is_valid_youtube_id(v.get(\"video_id\", \"\"))]\n",
                "\n",
                "    roteiro = RoteiroTutoria.model_validate(dados)\n",
                "    print(\"Roteiro carregado com sucesso. Agrupando e gerando PDFs...\")\n",
                "    gerar_pdfs(roteiro, PASTA_LIVROS, PASTA_SAIDA)\n",
                "    print(\"✅ Todos os PDFs foram gerados e salvos no Drive!\")\n",
                "\n",
                "exportar_pdfs_finais()\n"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "name": "Orquestrador_Automatico.ipynb",
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "colab", "Orquestrador_Automatico.ipynb"))
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print(f"Notebook gerado e salvo com sucesso em {out_path}")
