import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Orquestrador Automático de Tutoria (PBL)\n",
                "Este notebook extrai sumários de livros de medicina em PDF do Google Drive, mapeia objetivos usando a inteligência do Gemini (Google GenAI SDK), e gera PDFs consolidados com capas premium."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Instalação de Dependências\n",
                "!pip install pymupdf pypdf reportlab pydantic python-dotenv google-genai --quiet"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Montagem do Google Drive\n",
                "from google.colab import drive\n",
                "drive.mount('/content/drive')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Configuração da API do Gemini (Secrets)\n",
                "import os\n",
                "from google.colab import userdata\n",
                "os.environ['GEMINI_API_KEY'] = userdata.get('GEMINI_API_KEY')\n",
                "print('Chave configurada com sucesso!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Motor do Orquestrador\n",
                "import asyncio\n",
                "import logging\n",
                "import json\n",
                "import os\n",
                "import io\n",
                "import pydantic\n",
                "import fitz\n",
                "from google import genai\n",
                "from google.genai import types\n",
                "from pypdf import PdfReader, PdfWriter, PageObject\n",
                "from reportlab.pdfgen import canvas\n",
                "from reportlab.lib.pagesizes import A4\n",
                "from reportlab.lib import colors\n",
                "from reportlab.lib.units import inch\n",
                "\n",
                "logging.basicConfig(level=logging.INFO, format=\"%(levelname)s: %(message)s\")\n",
                "\n",
                "import typing\\n",
                "class Corte(pydantic.BaseModel):\\n",
                "    arquivo: str\\n",
                "    capitulo: str\\n",
                "    nivel: typing.Literal['conceito', 'mecanismo', 'clinica']\\n",
                "    pagina_inicial: int\\n",
                "    pagina_final: int\\n",
                "\\n",
                "class Objetivo(pydantic.BaseModel):\\n",
                "    numero: str\\n",
                "    titulo: str\\n",
                "    cortes: list[Corte]\\n",
                "\\n",
                "class RoteiroTutoria(pydantic.BaseModel):\\n",
                "    objetivos: list[Objetivo]\\n",
                "\n",
                "def draw_wrapped_text(c, text, width, x, y, font, size, line_height, color):\n",
                "    c.setFont(font, size)\n",
                "    c.setFillColor(color)\n",
                "    words = text.split(' ')\n",
                "    lines = []\n",
                "    current_line = []\n",
                "    for word in words:\n",
                "        current_line.append(word)\n",
                "        if c.stringWidth(' '.join(current_line), font, size) > width:\n",
                "            current_line.pop()\n",
                "            lines.append(' '.join(current_line))\n",
                "            current_line = [word]\n",
                "    if current_line:\n",
                "        lines.append(' '.join(current_line))\n",
                "    for line in lines:\n",
                "        c.drawString(x, y, line)\n",
                "        y -= line_height\n",
                "    return y\n",
                "\n",
                "def create_cover_page(objetivo_numero, objetivo_titulo):\\n",
                "    packet = io.BytesIO()\\n",
                "    c = canvas.Canvas(packet, pagesize=A4)\\n",
                "    width, height = A4\\n",
                "    c.setFillColorRGB(0.06, 0.09, 0.15)\\n",
                "    c.rect(0, 0, width, height, fill=1, stroke=0)\\n",
                "    c.setFillColorRGB(0.12, 0.53, 0.90)\\n",
                "    c.rect(0, 0, 15, height, fill=1, stroke=0)\\n",
                "    c.setFillColorRGB(1, 1, 1)\\n",
                "    c.setFont(\\\"Helvetica-Bold\\\", 46)\\n",
                "    c.drawString(60, height - 120, f\\\"OBJETIVO {objetivo_numero}\\\")\\n",
                "    c.setStrokeColorRGB(0.3, 0.3, 0.3)\\n",
                "    c.setLineWidth(1)\\n",
                "    c.line(60, height - 140, width - 60, height - 140)\\n",
                "    c.setFont(\\\"Helvetica\\\", 16)\\n",
                "    c.setFillColorRGB(0.6, 0.6, 0.6)\\n",
                "    c.drawString(60, height - 170, \\\"ROTEIRO DE TUTORIA - PBL\\\")\\n",
                "    draw_wrapped_text(c, objetivo_titulo, width - 120, 60, height - 230, \\\"Helvetica-Bold\\\", 22, 30, colors.white)\\n",
                "    c.setFont(\\\"Helvetica-Oblique\\\", 10)\\n",
                "    c.setFillColorRGB(0.4, 0.4, 0.4)\\n",
                "    c.drawString(60, 40, \\\"Gerado por Medhelp AI\\\")\\n",
                "    c.save()\\n",
                "    packet.seek(0)\\n",
                "    return PdfReader(packet).pages[0]\\n",
                "\\n",
                "def create_separator_page(livro, capitulo):\\n",
                "    packet = io.BytesIO()\\n",
                "    c = canvas.Canvas(packet, pagesize=A4)\\n",
                "    width, height = A4\\n",
                "    c.setFillColorRGB(0.1, 0.1, 0.12)\\n",
                "    c.rect(0, 0, width, height, fill=1, stroke=0)\\n",
                "    c.setFillColorRGB(0.12, 0.53, 0.90)\\n",
                "    c.rect(40, height/2 + 20, width - 80, 60, fill=1, stroke=0)\\n",
                "    c.setFillColorRGB(1, 1, 1)\\n",
                "    c.setFont(\\\"Helvetica-Bold\\\", 24)\\n",
                "    c.drawCentredString(width/2, height/2 + 40, \\\"REFERÊNCIA\\\")\\n",
                "    draw_wrapped_text(c, f\\\"{livro}\\\", width - 100, 50, height/2 - 20, \\\"Helvetica\\\", 16, 22, colors.lightgrey)\\n",
                "    draw_wrapped_text(c, capitulo, width - 100, 50, height/2 - 60, \\\"Helvetica-Bold\\\", 18, 26, colors.white)\\n",
                "    c.save()\\n",
                "    packet.seek(0)\\n",
                "    return PdfReader(packet).pages[0]\\n",
                "\n",
                "def get_pdfs_tocs(folder_path):\n",
                "    tocs = {}\n",
                "    for filename in os.listdir(folder_path):\n",
                "        if filename.lower().endswith(\".pdf\"):\n",
                "            filepath = os.path.join(folder_path, filename)\n",
                "            try:\n",
                "                doc = fitz.open(filepath)\n",
                "                tocs[filename] = doc.get_toc()\n",
                "                doc.close()\n",
                "            except Exception as e:\n",
                "                logging.error(f\"Erro ao ler TOC de {filename}: {e}\")\n",
                "    return tocs\n",
                "\n",
                "def merge_and_sort_cortes(cortes):\n",
                "    if not cortes: return []\n",
                "    from collections import defaultdict\n",
                "    grouped = defaultdict(list)\n",
                "    for c in cortes: grouped[c.arquivo].append(c)\n",
                "    merged = []\n",
                "    for arquivo, lista in grouped.items():\n",
                "        lista.sort(key=lambda x: x.pagina_inicial)\n",
                "        curr = lista[0]\n",
                "        for nxt in lista[1:]:\n",
                "            if nxt.pagina_inicial <= curr.pagina_final + 3:\n",
                "                curr.pagina_final = max(curr.pagina_final, nxt.pagina_final)\n",
                "            else:\n",
                "                merged.append(curr)\n",
                "                curr = nxt\n",
                "        merged.append(curr)\n",
                "    merged.sort(key=lambda x: {\"conceito\": 0, \"mecanismo\": 1, \"clinica\": 2}.get(x.nivel, 99))\n",
                "    return merged\n",
                "\n",
                "def gerar_pdfs(roteiro, pdfs_dir, output_dir):\n",
                "    os.makedirs(output_dir, exist_ok=True)\n",
                "    for obj in roteiro.objetivos:\n",
                "        obj_pdf_path = os.path.join(output_dir, f\"Objetivo {obj.numero}.pdf\")\n",
                "        writer = PdfWriter()\n",
                "        writer.add_page(create_cover_page(obj.numero, obj.titulo))\n",
                "        cortes = merge_and_sort_cortes(obj.cortes)\n",
                "        last_book_chapter = \"\"\n",
                "        for corte in cortes:\n",
                "            source_pdf = os.path.join(pdfs_dir, corte.arquivo)\n",
                "            if not os.path.exists(source_pdf): continue\n",
                "            curr_bc = f\"{corte.arquivo}_{corte.capitulo}\"\n",
                "            if curr_bc != last_book_chapter:\n",
                "                writer.add_page(create_separator_page(corte.arquivo, corte.capitulo))\n",
                "                last_book_chapter = curr_bc\n",
                "            reader = PdfReader(source_pdf)\n",
                "            p_ini, p_fim = max(0, corte.pagina_inicial - 1), min(len(reader.pages), corte.pagina_final)\n",
                "            for p_num in range(p_ini, p_fim): writer.add_page(reader.pages[p_num])\n",
                "        with open(obj_pdf_path, \"wb\") as f: writer.write(f)\n",
                "        logging.info(f\"Gerado: {obj_pdf_path}\")\n",
                "\n",
                "async def process_roteiro(objetivos_text, tocs):\n",
                "    contexto = \"SUMÁRIOS:\\n\"\n",
                "    for arquivo, toc in tocs.items():\n",
                "        if toc:\n",
                "            contexto += f\"Livro: {arquivo}\\n\"\n",
                "            for item in toc:\n",
                "                contexto += f\"{'  '*(item[0]-1)}- {item[1]} (Página: {item[2]})\\n\"\n",
                "    system_prompt = \"\"\"[O] - OBJETIVO\\n",
                "Você é um orquestrador cirúrgico de Roteiros de Tutoria (PBL) de Medicina. Sua função é mapear os Objetivos de Aprendizagem para as seções MAIS ESPECÍFICAS possíveis dentro dos sumários dos livros fornecidos.\\n\\n",
                "[C] - CONTEXTO\\n",
                "Você recebe os sumários (TOC) exatos dos livros em PDF. Cada item do sumário possui um nível hierárquico, título e página inicial.\\n\\n",
                "[A] - AÇÕES\\n",
                "1. Analise cada objetivo de aprendizagem.\\n",
                "2. Busque nos sumários a subseção exata que responde àquele objetivo.\\n",
                "3. Defina a `pagina_inicial` como a página da subseção escolhida.\\n",
                "4. Defina a `pagina_final` como a página do item IMEDIATAMENTE SEGUINTE no sumário, menos 1.\\n",
                "5. Classifique o nível didático do corte como 'conceito', 'mecanismo' ou 'clinica'.\\n\\n",
                "[N] - NORMAS (CRÍTICO)\\n",
                "- PROIBIDO mapear capítulos inteiros (ex: todo o Capítulo 15) se houver subseções específicas que respondam ao objetivo. Prefira sempre os tópicos mais profundos da hierarquia.\\n",
                "- PROIBIDO gerar cortes muito amplos. Faça cortes cirúrgicos (ex: 2 a 5 páginas). O aluno só precisa da parte exata que responde ao objetivo.\\n",
                "- PROIBIDO usar páginas que não existem no sumário fornecido.\\n",
                "- Se vários objetivos abordarem o mesmo grande tema, separe as subseções exatas (fatias) para cada um deles em vez de repetir o capítulo todo.\\n\\n",
                "[E] - EXEMPLOS (FEW-SHOT)\\n",
                "Objetivo: 'Tratamento da Abstinência Alcoólica'.\\n",
                "Sumário Fictício: Nível 1: Álcool (p.100). Nível 2: Intoxicação Aguda (p.102). Nível 2: Tratamento e Abstinência (p.108). Nível 2: Cirrose (p.115).\\n",
                "CERTO: pagina_inicial: 108, pagina_final: 114. (Focou na subseção exata)\\n",
                "ERRADO: pagina_inicial: 100, pagina_final: 114. (Pegou o capítulo todo, incluindo partes inúteis como Intoxicação)\\n\\n",
                "[S] - SAÍDA\\n",
                "Retorne estritamente os dados no formato estruturado solicitado.\"\"\"\n",
                "    api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "    client = genai.Client(api_key=api_key)\n",
                "    for tentativa in range(3):\n",
                "        try:\n",
                "            response = await client.aio.models.generate_content(\n",
                "                model='gemini-3.5-flash',\n",
                "                contents=f\"{contexto}\\n\\nOBJETIVOS:\\n{objetivos_text}\",\n",
                "                config=types.GenerateContentConfig(\n",
                "                    system_instruction=system_prompt,\n",
                "                    response_mime_type=\"application/json\",\n",
                "                    response_schema=RoteiroTutoria,\n",
                "                )\n",
                "            )\n",
                "            return response.parsed\n",
                "        except Exception as e:\n",
                "            logging.error(f\"Erro na API do Gemini (Tentativa {tentativa+1}/3): {e}\")\n",
                "            await asyncio.sleep(5)\n",
                "    return None\n",
                "\n",
                "async def run_medhelp(objetivos_text, refs_dir, out_dir):\n",
                "    tocs = get_pdfs_tocs(refs_dir)\n",
                "    data = await process_roteiro(objetivos_text, tocs)\n",
                "    if data:\n",
                "        gerar_pdfs(data, refs_dir, out_dir)\n",
                "        print('✅ Processamento 100% Finalizado!')\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. EXECUÇÃO DA TUTORIA\n",
                "# =========================\n",
                "PASTA_LIVROS = \"/content/drive/MyDrive/Logística - Drive/Tutoria/Referências - MEDICINA\"\n",
                "PASTA_SAIDA = \"/content/drive/MyDrive/Logística - Drive/Tutoria/saida/Tutoria_Teste\"\n",
                "\n",
                "OBJETIVOS = \"\"\"\n",
                "1. Descrever as drogas ilícitas mais comuns...\n",
                "2. Confrontar os conceitos clínicos e neurobiológicos...\n",
                "\"\"\"\n",
                "\n",
                "import nest_asyncio\n",
                "nest_asyncio.apply()\n",
                "import asyncio\n",
                "\n",
                "asyncio.run(run_medhelp(OBJETIVOS, PASTA_LIVROS, PASTA_SAIDA))\n"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "name": "Orquestrador_Automatico.ipynb",
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = '/home/vvgfilhos/medhelp/scripts/colab/Orquestrador_Automatico.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print(f"Notebook salvo em {out_path}")
