import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Orquestrador Automático de Tutoria (PBL)\n",
                "Este notebook extrai sumários de livros de medicina em PDF do Google Drive, mapeia objetivos usando a inteligência do Gemini (Google GenAI SDK), e gera PDFs consolidados com capas premium."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Instalação de Dependências\n",
                "!pip install pymupdf pypdf reportlab pydantic python-dotenv google-genai --quiet"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Montagem do Google Drive\n",
                "from google.colab import drive\n",
                "drive.mount('/content/drive')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Configuração da API do Gemini (Secrets)\n",
                "import os\n",
                "from google.colab import userdata\n",
                "os.environ['GEMINI_API_KEY'] = userdata.get('GEMINI_API_KEY')\n",
                "print('Chave configurada com sucesso!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Motor do Orquestrador\n",
                "import asyncio\n",
                "import logging\n",
                "import json\n",
                "import os\n",
                "import io\n",
                "import pydantic\n",
                "import fitz\n",
                "from google import genai\n",
                "from google.genai import types\n",
                "from pypdf import PdfReader, PdfWriter, PageObject\n",
                "from reportlab.pdfgen import canvas\n",
                "from reportlab.lib.pagesizes import A4\n",
                "from reportlab.lib import colors\n",
                "from reportlab.lib.units import inch\n",
                "\n",
                "logging.basicConfig(level=logging.INFO, format=\"%(levelname)s: %(message)s\")\n",
                "\n",
                "import typing\n",
                "class Corte(pydantic.BaseModel):\n",
                "    arquivo: str\n",
                "    capitulo: str\n",
                "    nivel: typing.Literal['conceito', 'mecanismo', 'clinica']\n",
                "    pagina_inicial: int\n",
                "    pagina_final: int\n",
                "\n",
                "class Objetivo(pydantic.BaseModel):\n",
                "    numero: str\n",
                "    titulo: str\n",
                "    cortes: list[Corte]\n",
                "\n",
                "class RoteiroTutoria(pydantic.BaseModel):\n",
                "    objetivos: list[Objetivo]\n",
                "\n",
                "class RefinamentoCorte(pydantic.BaseModel):\n",
                "    relevante: bool\n",
                "    pagina_inicial_refinada: int\n",
                "    pagina_final_refinada: int\n",
                "\n",
                "def draw_wrapped_text(c, text, width, x, y, font, size, line_height, color):\n",
                "    c.setFont(font, size)\n",
                "    c.setFillColor(color)\n",
                "    words = text.split(' ')\n",
                "    lines = []\n",
                "    current_line = []\n",
                "    for word in words:\n",
                "        current_line.append(word)\n",
                "        if c.stringWidth(' '.join(current_line), font, size) > width:\n",
                "            current_line.pop()\n",
                "            lines.append(' '.join(current_line))\n",
                "            current_line = [word]\n",
                "    if current_line:\n",
                "        lines.append(' '.join(current_line))\n",
                "    for line in lines:\n",
                "        c.drawString(x, y, line)\n",
                "        y -= line_height\n",
                "    return y\n",
                "\n",
                "def create_cover_page(objetivo_numero, objetivo_titulo):\n",
                "    packet = io.BytesIO()\n",
                "    c = canvas.Canvas(packet, pagesize=A4)\n",
                "    width, height = A4\n",
                "    c.setFillColorRGB(1, 1, 1)\n",
                "    c.rect(0, 0, width, height, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(0.12, 0.53, 0.90)\n",
                "    c.rect(0, 0, 15, height, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(0.1, 0.1, 0.1)\n",
                "    c.setFont(\"Helvetica-Bold\", 46)\n",
                "    c.drawString(60, height - 120, f\"OBJETIVO {objetivo_numero}\")\n",
                "    c.setStrokeColorRGB(0.8, 0.8, 0.8)\n",
                "    c.setLineWidth(1)\n",
                "    c.line(60, height - 140, width - 60, height - 140)\n",
                "    c.setFont(\"Helvetica\", 16)\n",
                "    c.setFillColorRGB(0.4, 0.4, 0.4)\n",
                "    c.drawString(60, height - 170, \"ROTEIRO DE TUTORIA - PBL\")\n",
                "    draw_wrapped_text(c, objetivo_titulo, width - 120, 60, height - 230, \"Helvetica-Bold\", 22, 30, colors.black)\n",
                "    c.setFont(\"Helvetica-Oblique\", 10)\n",
                "    c.setFillColorRGB(0.6, 0.6, 0.6)\n",
                "    c.drawString(60, 40, \"© Conteúdo Autoral • João Gabriel R. Trovão\")\n",
                "    c.save()\n",
                "    packet.seek(0)\n",
                "    return PdfReader(packet).pages[0]\n",
                "\n",
                "def create_separator_page(livro, capitulo):\n",
                "    packet = io.BytesIO()\n",
                "    c = canvas.Canvas(packet, pagesize=A4)\n",
                "    width, height = A4\n",
                "    c.setFillColorRGB(1, 1, 1)\n",
                "    c.rect(0, 0, width, height, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(0.12, 0.53, 0.90)\n",
                "    c.rect(40, height/2 + 20, width - 80, 60, fill=1, stroke=0)\n",
                "    c.setFillColorRGB(1, 1, 1)\n",
                "    c.setFont(\"Helvetica-Bold\", 24)\n",
                "    c.drawCentredString(width/2, height/2 + 40, \"REFERÊNCIA\")\n",
                "    draw_wrapped_text(c, f\"{livro}\", width - 100, 50, height/2 - 20, \"Helvetica\", 16, 22, colors.dimgrey)\n",
                "    draw_wrapped_text(c, capitulo, width - 100, 50, height/2 - 60, \"Helvetica-Bold\", 18, 26, colors.black)\n",
                "    c.save()\n",
                "    packet.seek(0)\n",
                "    return PdfReader(packet).pages[0]\n",
                "\n",
                "def get_pdfs_tocs(folder_path):\n",
                "    tocs = {}\n",
                "    for filename in os.listdir(folder_path):\n",
                "        if filename.lower().endswith(\".pdf\"):\n",
                "            filepath = os.path.join(folder_path, filename)\n",
                "            try:\n",
                "                doc = fitz.open(filepath)\n",
                "                tocs[filename] = doc.get_toc()\n",
                "                doc.close()\n",
                "            except Exception as e:\n",
                "                logging.error(f\"Erro ao ler TOC de {filename}: {e}\")\n",
                "    return tocs\n",
                "\n",
                "def merge_and_sort_cortes(cortes):\n",
                "    if not cortes: return []\n",
                "    from collections import defaultdict\n",
                "    grouped = defaultdict(list)\n",
                "    for c in cortes: grouped[c.arquivo].append(c)\n",
                "    merged = []\n",
                "    for arquivo, lista in grouped.items():\n",
                "        lista.sort(key=lambda x: x.pagina_inicial)\n",
                "        curr = lista[0]\n",
                "        for nxt in lista[1:]:\n",
                "            if nxt.pagina_inicial <= curr.pagina_final + 1:\n",
                "                curr.pagina_final = max(curr.pagina_final, nxt.pagina_final)\n",
                "            else:\n",
                "                merged.append(curr)\n",
                "                curr = nxt\n",
                "        merged.append(curr)\n",
                "    merged.sort(key=lambda x: {\"conceito\": 0, \"mecanismo\": 1, \"clinica\": 2}.get(x.nivel, 99))\n",
                "    return merged\n",
                "\n",
                "def agrupar_objetivos(objetivos):\n",
                "    def get_pages(obj):\n",
                "        pages = set()\n",
                "        for c in obj.cortes:\n",
                "            for p in range(c.pagina_inicial, max(c.pagina_inicial, c.pagina_final) + 1):\n",
                "                pages.add(f\"{c.arquivo}_{p}\")\n",
                "        return pages\n",
                "    grupos = []\n",
                "    for obj in objetivos:\n",
                "        merged = False\n",
                "        obj_pages = get_pages(obj)\n",
                "        for grupo in grupos:\n",
                "            grupo_pages = set()\n",
                "            for g_obj in grupo:\n",
                "                grupo_pages.update(get_pages(g_obj))\n",
                "            if not obj_pages or not grupo_pages: continue\n",
                "            overlap = len(obj_pages.intersection(grupo_pages)) / len(obj_pages.union(grupo_pages))\n",
                "            if overlap > 0.3:\n",
                "                grupo.append(obj)\n",
                "                merged = True\n",
                "                break\n",
                "        if not merged:\n",
                "            grupos.append([obj])\n",
                "    objetivos_mesclados = []\n",
                "    for grupo in grupos:\n",
                "        if len(grupo) == 1:\n",
                "            objetivos_mesclados.append(grupo[0])\n",
                "        else:\n",
                "            numeros = \" e \".join([g.numero for g in grupo])\n",
                "            titulo = \"  |  \".join([f\"[{g.numero}] {g.titulo}\" for g in grupo])\n",
                "            cortes = []\n",
                "            for g in grupo: cortes.extend(g.cortes)\n",
                "            objetivos_mesclados.append(Objetivo(numero=numeros, titulo=titulo, cortes=cortes))\n",
                "    return objetivos_mesclados\n",
                "\n",
                "def gerar_pdfs(roteiro, pdfs_dir, output_dir):\n",
                "    os.makedirs(output_dir, exist_ok=True)\n",
                "    objetivos_processados = agrupar_objetivos(roteiro.objetivos)\n",
                "    for obj in objetivos_processados:\n",
                "        obj_pdf_path = os.path.join(output_dir, f\"Objetivo {obj.numero}.pdf\")\n",
                "        writer = PdfWriter()\n",
                "        writer.add_page(create_cover_page(obj.numero, obj.titulo))\n",
                "        cortes = merge_and_sort_cortes(obj.cortes)\n",
                "        last_book_chapter = \"\"\n",
                "        for corte in cortes:\n",
                "            source_pdf = os.path.join(pdfs_dir, corte.arquivo)\n",
                "            if not os.path.exists(source_pdf): continue\n",
                "            curr_bc = f\"{corte.arquivo}_{corte.capitulo}\"\n",
                "            if curr_bc != last_book_chapter:\n",
                "                writer.add_page(create_separator_page(corte.arquivo, corte.capitulo))\n",
                "                last_book_chapter = curr_bc\n",
                "            reader = PdfReader(source_pdf)\n",
                "            p_ini, p_fim = max(0, corte.pagina_inicial - 1), min(len(reader.pages), max(corte.pagina_inicial, corte.pagina_final))\n",
                "            for p_num in range(p_ini, p_fim): writer.add_page(reader.pages[p_num])\n",
                "        with open(obj_pdf_path, \"wb\") as f: writer.write(f)\n",
                "        logging.info(f\"Gerado: {obj_pdf_path}\")\n",
                "\n",
                "async def process_roteiro(objetivos_text, tocs):\n",
                "    contexto = \"SUMÁRIOS:\\n\"\n",
                "    for arquivo, toc in tocs.items():\n",
                "        if toc:\n",
                "            contexto += f\"Livro: {arquivo}\\n\"\n",
                "            for item in toc:\n",
                "                contexto += f\"{'  '*(item[0]-1)}- {item[1]} (Página: {item[2]})\\n\"\n",
                "    system_prompt = \"\"\"[O] - OBJETIVO\n",
                "Você é um orquestrador cirúrgico de Roteiros de Tutoria (PBL) de Medicina. Sua função é mapear os Objetivos de Aprendizagem para as seções MAIS ESPECÍFICAS possíveis dentro dos sumários dos livros fornecidos.\n\n",
                "[C] - CONTEXTO\n",
                "Você recebe os sumários (TOC) exatos dos livros em PDF. Cada item do sumário possui um nível hierárquico, título e página inicial.\n\n",
                "[A] - AÇÕES\n",
                "1. Analise cada objetivo de aprendizagem.\n",
                "2. Busque nos sumários a subseção exata que responde àquele objetivo.\n",
                "3. Defina a `pagina_inicial` como a página da subseção escolhida.\n",
                "4. Defina a `pagina_final` como a página do item IMEDIATAMENTE SEGUINTE no sumário, menos 1.\n",
                "5. Classifique o nível didático do corte como 'conceito', 'mecanismo' ou 'clinica'.\n\n",
                "[N] - NORMAS (CRÍTICO)\n",
                "- PROIBIDO mapear capítulos inteiros (ex: todo o Capítulo 15) se houver subseções específicas que respondam ao objetivo. Prefira sempre os tópicos mais profundos da hierarquia.\n",
                "- PROIBIDO gerar cortes muito amplos. Faça cortes cirúrgicos (ex: 2 a 5 páginas). O aluno só precisa da parte exata que responde ao objetivo.\n",
                "- PROIBIDO usar páginas que não existem no sumário fornecido.\n",
                "- Se um objetivo pedir temas distintos (ex: álcool, maconha e cocaína) que estão em páginas separadas do mesmo livro, crie OBJETOS Corte SEPARADOS para cada tema. NUNCA crie um único corte gigante englobando os três.\n\n",
                "[E] - EXEMPLOS (FEW-SHOT)\n",
                "Objetivo: 'Efeitos da Maconha e Cocaína'.\n",
                "Sumário Fictício: Nível 1: Drogas. Nível 2: Cocaína (p.50). Nível 2: Heroína (p.60). Nível 2: Maconha (p.70). Nível 2: Álcool (p.80).\n",
                "CERTO: Retorna 2 objetos Corte independentes: um de p.50 até 59 e outro de p.70 até 79.\n",
                "ERRADO: Retorna 1 corte gigante de p.50 até 79 (englobando Heroína inutilmente).\n\n",
                "[S] - SAÍDA\n",
                "Retorne estritamente os dados no formato estruturado solicitado.\"\"\"\n",
                "    api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "    client = genai.Client(api_key=api_key)\n",
                "    for tentativa in range(3):\n",
                "        try:\n",
                "            response = await client.aio.models.generate_content(\n",
                "                model='gemini-3.5-flash',\n",
                "                contents=f\"{contexto}\\n\\nOBJETIVOS:\\n{objetivos_text}\",\n",
                "                config=types.GenerateContentConfig(\n",
                "                    system_instruction=system_prompt,\n",
                "                    response_mime_type=\"application/json\",\n",
                "                    response_schema=RoteiroTutoria,\n",
                "                )\n",
                "            )\n",
                "            if not response.parsed:\n",
                "                raise ValueError(\"O modelo não retornou um JSON válido que obedeça ao Schema.\")\n",
                "            return response.parsed\n",
                "        except Exception as e:\n",
                "            logging.error(f\"Erro na API do Gemini (Tentativa {tentativa+1}/3): {e}\")\n",
                "            await asyncio.sleep(5)\n",
                "    return None\n",
                "\n",
                "def extrair_texto_paginas(pdf_path, p_ini, p_fim):\n",
                "    try:\n",
                "        doc = fitz.open(pdf_path)\n",
                "        text = \"\"\n",
                "        start = max(0, p_ini - 1)\n",
                "        end = min(len(doc), max(p_ini, p_fim))\n",
                "        for i in range(start, end):\n",
                "            text += f\"\\n--- PÁGINA {i+1} ---\\n\"\n",
                "            text += doc[i].get_text(\"text\")\n",
                "        doc.close()\n",
                "        return text\n",
                "    except Exception as e:\n",
                "        logging.error(f\"Erro extraindo texto: {e}\")\n",
                "        return \"\"\n",
                "\n",
                "async def refinar_roteiro(roteiro, refs_dir):\n",
                "    api_key = os.environ.get(\"GEMINI_API_KEY\")\n",
                "    client = genai.Client(api_key=api_key)\n",
                "    sys_prompt = \"\"\"[O] - OBJETIVO\\n",
                "Atue como um refinador algorítmico de cortes de leitura (PBL). Sua missão é extrair exatamente UM BLOCO ÚNICO CONTÍGUO de páginas que possua densidade informacional máxima para responder ao objetivo, minimizando o ruído.\\n",
                "[C] - CONTEXTO\\n",
                "Você recebe dois dados de entrada (Ground Truth):\\n",
                "1. O Objetivo de Aprendizagem.\\n",
                "2. O Texto Extraído do livro, onde cada transição de página é rigorosamente demarcada pelo marcador '--- PÁGINA X ---'. O texto das páginas reflete o layout real (com cabeçalhos, rodapés e quebras de linha).\\n",
                "[A] - AÇÕES\\n",
                "Pense passo a passo:\\n",
                "1. Desconstrua o objetivo do aluno para encontrar sua espinha dorsal semântica (o foco clínico, patológico ou farmacológico real).\\n",
                "2. Varra o Texto Extraído buscando a PRIMEIRA PÁGINA exata onde esse núcleo semântico começa a ser tecnicamente conceituado. Salve-a como `pagina_inicial_refinada`.\\n",
                "3. Avance a leitura a partir da página inicial. Pare IMEDIATAMENTE e marque a página atual como `pagina_final_refinada` se UMA das seguintes condições for atendida:\\n",
                "   a) Um novo subtítulo primário indicar uma mudança radical de assunto (ex: fim da seção de Cocaína e início da seção de Heroína).\\n",
                "   b) A densidade de texto útil (diretamente relacionado ao objetivo) na página cair para menos de 30%.\\n",
                "4. Caso o texto inteiro seja irrelevante ou tangencial ao objetivo, rejeite o bloco inteiro (relevante: false).\\n",
                "[N] - NORMAS (CRÍTICO)\\n",
                "- NEGATIVO: NUNCA crie múltiplos blocos. Retorne apenas UM bloco contíguo único para não quebrar a fluidez de leitura.\\n",
                "- NEGATIVO: NUNCA invente ou adivinhe números de página. Os números DEVEM ser estritamente os mesmos extraídos da tag '--- PÁGINA X ---'.\\n",
                "- NEGATIVO: Se o texto for puramente histórico, epidemiológico anedótico ou não abordar o objetivo de forma técnica, você DEVE retornar `relevante: false` e páginas como 0.\\n",
                "- POSITIVO: Seja cirúrgico (idealmente cortes de 1 a 6 páginas). Corte a \"gordura\" sem piedade.\\n",
                "- POSITIVO: Se a resposta real está apenas em um parágrafo isolado na página 50, retorne inicial 50 e final 50.\\n",
                "[E] - EXEMPLOS\\n",
                "Input (Simplificado):\\n",
                "Objetivo: \"Diferenciar tolerância de abstinência.\"\\n",
                "Texto Extraído: \\n",
                "--- PÁGINA 10 ---\\n",
                "Introdução. Histórico das drogas.\\n",
                "--- PÁGINA 11 ---\\n",
                "Tolerância: necessidade de doses maiores...\\n",
                "--- PÁGINA 12 ---\\n",
                "Síndrome de Abstinência: sinais e sintomas...\\n",
                "--- PÁGINA 13 ---\\n",
                "Tratamento e desintoxicação.\\n",
                "\\n",
                "Chain of Thought & Output:\\n",
                "Raciocínio: A página 10 é gordura histórica. O núcleo inicia na 11 e se estende até a 12. A página 13 aborda tratamento, que é um novo assunto primário que foge de \"diferenciar tolerância de abstinência\". O corte deve ser 11 a 12.\\n",
                "Resultado: `relevante: true`, `pagina_inicial_refinada: 11`, `pagina_final_refinada: 12`.\\n",
                "[S] - SAÍDA\\n",
                "Retorne OBRIGATORIAMENTE os dados estruturados conforme o JSON Schema exigido pela API (`RefinamentoCorte`), sem explicações adicionais ou saudações.\\n",
                "\"\"\"\n",
                "    for obj in roteiro.objetivos:\n",
                "        novos_cortes = []\n",
                "        for corte in obj.cortes:\n",
                "            source_pdf = os.path.join(refs_dir, corte.arquivo)\n",
                "            if not os.path.exists(source_pdf):\n",
                "                novos_cortes.append(corte)\n",
                "                continue\n",
                "            texto = extrair_texto_paginas(source_pdf, corte.pagina_inicial, corte.pagina_final)\n",
                "            if not texto.strip():\n",
                "                novos_cortes.append(corte)\n",
                "                continue\n",
                "            prompt = f\"OBJETIVO: {obj.titulo}\\n\\nTEXTO EXTRAÍDO:\\n{texto[:150000]}\"\n",
                "            for tentativa in range(3):\n",
                "                try:\n",
                "                    response = await client.aio.models.generate_content(\n",
                "                        model='gemini-3.5-flash',\n",
                "                        contents=prompt,\n",
                "                        config=types.GenerateContentConfig(\n",
                "                            system_instruction=sys_prompt,\n",
                "                            response_mime_type=\"application/json\",\n",
                "                            response_schema=RefinamentoCorte,\n",
                "                        )\n",
                "                    )\n",
                "                    if not response.parsed:\n",
                "                        raise ValueError(\"Parse nulo.\")\n",
                "                    if response.parsed.relevante:\n",
                "                        corte.pagina_inicial = response.parsed.pagina_inicial_refinada\n",
                "                        corte.pagina_final = response.parsed.pagina_final_refinada\n",
                "                        novos_cortes.append(corte)\n",
                "                    break\n",
                "                except Exception as e:\n",
                "                    logging.error(f\"Erro no Refino (Tentativa {tentativa+1}): {e}\")\n",
                "                    await asyncio.sleep(3)\n",
                "            else:\n",
                "                novos_cortes.append(corte)\n",
                "        obj.cortes = novos_cortes\n",
                "    return roteiro\n",
                "\n",
                "async def gerar_esboco(objetivos_text, refs_dir):\n",
                "    print(\"Analisando sumários e consultando a API do Gemini (Agente 1)...\")\n",
                "    tocs = get_pdfs_tocs(refs_dir)\n",
                "    roteiro = await process_roteiro(objetivos_text, tocs)\n",
                "    if roteiro:\n",
                "        print(\"Refinando cortes através de leitura de texto (Agente 2)...\")\n",
                "        roteiro = await refinar_roteiro(roteiro, refs_dir)\n",
                "        with open('roteiro_revisao.json', 'w', encoding='utf-8') as f:\n",
                "            f.write(roteiro.model_dump_json(indent=4))\n",
                "        print(\"✅ Esboço gerado com sucesso!\")\n",
                "        print(\"👉 Dê um clique duplo no arquivo 'roteiro_revisao.json' no menu de Arquivos à esquerda.\")\n",
                "        print(\"👉 Revise as páginas e os cortes. Se algo estiver errado, altere os números e salve (Ctrl+S).\")\n",
                "        print(\"👉 Depois de salvar, rode a célula '6. EXPORTAR PDFs FINAIS'.\")\n",
                "    else:\n",
                "        print(\"❌ Falha ao gerar o roteiro.\")\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. INSERIR OBJETIVOS E GERAR ESBOÇO\n",
                "# ===================================\n",
                "PASTA_LIVROS = \"/content/drive/MyDrive/Logística - Drive/Tutoria/Referências - MEDICINA\"\n",
                "PASTA_SAIDA = \"/content/drive/MyDrive/Logística - Drive/Tutoria/saida/Tutoria_Teste\"\n",
                "\n",
                "OBJETIVOS = \"\"\"\n",
                "1. Descrever as drogas ilícitas mais comuns...\n",
                "2. Confrontar os conceitos clínicos e neurobiológicos...\n",
                "\"\"\"\n",
                "\n",
                "import nest_asyncio\n",
                "nest_asyncio.apply()\n",
                "import asyncio\n",
                "\n",
                "asyncio.run(gerar_esboco(OBJETIVOS, PASTA_LIVROS))\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. EXPORTAR PDFs FINAIS (Após sua revisão!)\n",
                "# ==========================================\n",
                "import json\n",
                "import os\n",
                "\n",
                "def exportar_pdfs_finais():\n",
                "    print(\"Lendo roteiro_revisao.json...\")\n",
                "    if not os.path.exists('roteiro_revisao.json'):\n",
                "        print(\"❌ Erro: Arquivo roteiro_revisao.json não encontrado. Rode a célula 5 primeiro.\")\n",
                "        return\n",
                "        \n",
                "    with open('roteiro_revisao.json', 'r', encoding='utf-8') as f:\n",
                "        dados = json.load(f)\n",
                "        \n",
                "    roteiro = RoteiroTutoria.model_validate(dados)\n",
                "    print(\"Roteiro carregado com sucesso. Agrupando e gerando PDFs...\")\n",
                "    gerar_pdfs(roteiro, PASTA_LIVROS, PASTA_SAIDA)\n",
                "    print(\"✅ Todos os PDFs foram gerados e salvos no Drive!\")\n",
                "\n",
                "exportar_pdfs_finais()\n"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "name": "Orquestrador_Automatico.ipynb",
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = '/home/vvgfilhos/medhelp/scripts/colab/Orquestrador_Automatico.ipynb'
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)
print(f"Notebook salvo em {out_path}")
